import { CardProduct } from "@/app/lib/types";

export const CARDS: CardProduct[] = [
  {
    id: "citi-double-cash",
    name: "Citi Double Cash® (example)",
    issuer: "Citi",
    network: "Mastercard",
    annualFee: 0,
    fxFeePercent: 0.03,
    baseAPRRange: "See issuer for current APR",
    creditFit: ["fair", "good", "excellent"],
    rewards: [{ category: "all", rate: 0.02, details: "Flat 2% cash back" }],
    complexity: "simple",
    asOf: "2025-09-05",
  },
  {
    id: "wells-active-cash",
    name: "Wells Fargo Active Cash® (example)",
    issuer: "Wells Fargo",
    network: "Visa",
    annualFee: 0,
    fxFeePercent: 0.03,
    baseAPRRange: "See issuer for current APR",
    creditFit: ["good", "excellent"],
    rewards: [{ category: "all", rate: 0.02 }],
    signupBonus: { amountCash: 200, spendRequirement: 1000, windowDays: 90 },
    complexity: "simple",
    asOf: "2025-09-05",
  },
  {
    id: "discover-it-student",
    name: "Discover it® Student Cash Back (example)",
    issuer: "Discover",
    network: "Discover",
    annualFee: 0,
    fxFeePercent: 0,
    baseAPRRange: "See issuer",
    creditFit: ["student", "new"],
    studentEligible: true,
    rewards: [
      { category: "all", rate: 0.01, details: "1% base; 5% rotating categories (activation)" },
      { category: "dining", rate: 0.05, capAnnual: 6000 },
      { category: "groceries", rate: 0.05, capAnnual: 6000 },
    ],
    complexity: "rotating",
    asOf: "2025-09-05",
  },
  {
    id: "capone-savorone-student",
    name: "Capital One SavorOne Student (example)",
    issuer: "Capital One",
    network: "Mastercard",
    annualFee: 0,
    fxFeePercent: 0,
    baseAPRRange: "See issuer",
    creditFit: ["student", "new"],
    studentEligible: true,
    rewards: [
      { category: "all", rate: 0.01 },
      { category: "dining", rate: 0.03 },
      { category: "transit", rate: 0.03 },
    ],
    complexity: "tiered",
    asOf: "2025-09-05",
  },
  {
    id: "boa-customized-student",
    name: "BofA Customized Cash Rewards Student (example)",
    issuer: "Bank of America",
    network: "Visa",
    annualFee: 0,
    fxFeePercent: 0.03,
    baseAPRRange: "See issuer",
    creditFit: ["student", "new", "fair"],
    studentEligible: true,
    rewards: [
      { category: "all", rate: 0.01 },
      { category: "groceries", rate: 0.03 },
      { category: "gas", rate: 0.03 },
      { category: "dining", rate: 0.03 },
    ],
    complexity: "tiered",
    asOf: "2025-09-05",
  },
  {
    id: "chase-freedom-unlimited",
    name: "Chase Freedom Unlimited® (example)",
    issuer: "Chase",
    network: "Visa",
    annualFee: 0,
    fxFeePercent: 0.03,
    baseAPRRange: "See issuer",
    creditFit: ["good", "excellent"],
    rewards: [
      { category: "all", rate: 0.015 },
      { category: "dining", rate: 0.03 },
      { category: "travel", rate: 0.05, details: "Via issuer portal (example)" },
    ],
    signupBonus: { amountCash: 200, spendRequirement: 500, windowDays: 90 },
    complexity: "tiered",
    asOf: "2025-09-05",
  },
];
